version: '3.1'

services:
  db-django:
    image: simonowens157/postgresql:v1.0
    restart: always
    container_name: db_django
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ${PWD}/data/:/var/lib/postgresql_data
    networks:
      - djangonet

  nginx-django:
    image: simonowens157/nginx:latest
    container_name: nginx_django
    restart: always
    networks:
    - djangonet
  
  web-django:
    image: simonowens157/django:v1.0
    container_name: web_django
    restart: always
    command: bash -c "sh production_deploy.sh && sh start-django.sh"
    volumes:
      - ${PWD}/build/code/:/code
    networks:
      - djangonet
    depends_on:
      - db_django
      - nginx
    
networks:
  default:
    external:
      name: gateway